### PR TITLE
Fix copy issus

### PR DESCRIPTION
**Pull request by runbb**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Can you please elaborate a bit?

**Comment by runbb** [comment]
old code
```typescript
      var pasteboard = utils.ios.getter(UIPasteboard, UIPasteboard.generalPasteboard);
      var content = pasteboard.valueForPasteboardType(kUTTypePlainText);
```

return null

But I've fixed the problem
Replace the old code with this
```typescript
      var content = pasteboard.string || pasteboard.valueForPasteboardType(kUTTypePlainText);
```

**Comment by EddyVerbruggen** [comment]
Ah so it may return `null`. I didn't notice that `.string` method in the iOS SDK's before but indeed [it's there](https://developer.apple.com/documentation/uikit/uipasteboard/1622092-string?language=objc)!

Thank you for sharing your fix 💪

**Comment by EddyVerbruggen** [comment]
It's available on npm in version 1.1.7 now! 🎉

**Pull request merged**
